### ISSUE TITLE
Error when tap done!

### ISSUE THREAD

**Issue by jxhno1** [pressanykeyplease/RoomPlan-Sandbox#1]
Room_Plan/PlanViewerViewController.swift:22: Fatal error: Walls_grp not found

**Comment by pressanykeyplease** [comment]
> Room_Plan/PlanViewerViewController.swift:22: Fatal error: Walls_grp not found

Hey, please send your device name

**Comment by jxhno1** [comment]
Give me a pardon？I use iPad pro （11inch）3rd generation ipados16.1

**Comment by pressanykeyplease** [comment]
> Give me a pardon？I use iPad pro （11inch）3rd generation ipados16.1

I haven't tested that on iPad. Steps you can try:

1. Increase a processing delay (currently it is 3 sec)
2. Try to use only one room
3. Export your scan to a file and check if it contains `Walls_grp` folder

**Comment by jxhno1** [comment]
Thank you for your suggestions！let me try it later。

**Comment by jxhno1** [comment]
And I want to ask you， how to Export my scan to a file and check if it contains Walls_grp folder？

**Comment by jxhno1** [comment]
And I want to ask you， how to Export my scan to a file and check if it contains Walls_grp folder？

**Comment by jzz123** [comment]
How to save the usdz file that wall depth can also be show like yours?

**Comment by pressanykeyplease** [comment]
@jzz123 @jxhno1 please check Apple's [demo project](https://developer.apple.com/documentation/roomplan/create_a_3d_model_of_an_interior_room_by_guiding_the_user_through_an_ar_experience) - it contains exporting feature.

**Comment by jxhno1** [comment]
Thank you for your help, we will try to check them.
