### ISSUE TITLE
How to save the usdz file that wall depth can also be show like yours? 

### ISSUE THREAD

**Issue by jzz123** [pressanykeyplease/RoomPlan-Sandbox#2]
How to save the usdz file that wall depth can also be show like yours?

**Comment by pressanykeyplease** [comment]
Check Apple's [sample project](https://developer.apple.com/documentation/roomplan/create_a_3d_model_of_an_interior_room_by_guiding_the_user_through_an_ar_experience) to find out how to export USDZ file. My repo only shows the way to display walls from scanned room.
